[package]
name = "rusty_spark_benchmark"
version = "0.1.0"
authors = ["ParzivalSec <lukas.vogl12@gmail.com>"]

[dependencies]
spark_core = { path = "spark_core" }
mem = { path = "mem" }
container = { path = "container" }
time = "0.1"

[workspace]